insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Lodovico', 'lcavell0@weather.com', '762-653-1506', '26459 Stang Drive', 'Friends');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Malina', 'mkynan1@istockphoto.com', '253-233-4992', '09432 Manufacturers Court', 'Other');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Kathie', 'kwestcarr2@nytimes.com', '246-690-2741', '65 Blackbird Trail', 'Work');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Chrystal', 'cstandring3@mapquest.com', '790-766-9181', '6 Morning Road', 'Family');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Viv', 'voxborough4@slashdot.org', '797-961-3536', '183 Lunder Trail', 'Family');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Joyce', 'jfrankish5@cafepress.com', '731-597-3997', '16567 Waxwing Point', 'Work');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Gaye', 'gferrers6@smugmug.com', '791-387-4799', '18887 Pine View Crossing', 'Other');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Fedora', 'fmacauley7@chronoengine.com', '883-990-5430', '20375 Westridge Plaza', 'School');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Kyrstin', 'kkeys8@mayoclinic.com', '869-945-4203', '3 Summerview Junction', 'Family');
insert into Contacts (Name, Email, Phone, Address, Group_Name) values ('Ingaberg', 'ihow9@wiley.com', '370-489-3800', '7994 Coleman Way', 'Work');
